blank_issues_enabled: false

defaults:
  - template: 'bug_report.yml'
    name: 'ğŸ› Bug'
    about: 'ãƒã‚°å ±å‘Šç”¨ã®èª²é¡Œ'
  - template: 'feature_request.yml'
    name: 'ğŸ’¡ Feature Request'
    about: 'æ©Ÿèƒ½è¿½åŠ ç”¨ã®èª²é¡Œ'
  - template: 'apple_store_review_problem.yml'
    name: 'ğŸ’¡ AppleStore Review Problem'
    about: 'AppleStoreã‹ã‚‰æŒ‡æ‘˜ã•ã‚ŒãŸå ´åˆã«ç«‹ã¦ã‚‹èª²é¡Œ'
