blank_issues_enabled: false


defaults:
  - template: "bug_report.yml"
    name: "ğŸ› Bug"
    about: "Report a bug"
  - template: "feature_request.yml"
    name: "ğŸ’¡ Feature Request"
    about: "Suggest a new feature"

